### PR TITLE
Typo  error : Update precompile.mdx

### PR DESCRIPTION
**Pull request by othernamesweretaken**
"provides" typo correction

### CODE REVIEW

**Review by DZGoldman — APPROVED** [review]

**Comment by DZGoldman** [comment]
@othernamesweretaken ty - can you sign the CLA please?

**Comment by othernamesweretaken** [comment]
@DZGoldman : Any chances for anonymity?

**Comment by othernamesweretaken** [comment]
@DZGoldman - I have signed CLA, Can you please check and confirm?

**Review by DZGoldman — APPROVED** [review]

**Comment by DZGoldman** [comment]
@othernamesweretaken got it, ty!

**Pull request merged**
