### PR TITLE
added usdc quickstart

### PR DESCRIPTION
**Pull request by circle-ccooper**
1. Audience: Who am I writing for? **Developers**
2. Problem: What specific problem are they trying to solve? **Teaching new developers how to transfer USDC over Arbitrum network**
3. Discovery: How are they looking for a solution to this problem? **Developers are searching dev docs** What search terms are they using? **USDC transfer, send USDC, USDC functions**
4. Document type: Which document type is most suitable? **Quickstart**
5. Policy acknowledgment (Third-party docs only): Do you agree to the third-party content policy outlined within "Contribute docs"? **N/A**

### CODE REVIEW

**Comment by anegg0** [comment]
@circle-ccooper, thank you for submitting!
The next steps in the submission process:
- Please sign the CLA (above).
- The TW team will do an editorial review to ensure your content meets OCL's pattern guide.
- You can approve or reject the suggested editorial nits
- Content gets merged!

**Comment by hkalodner** [comment]
@cla-bot check

**Review by anegg0 — APPROVED** [review]
LGTM

**Review by anegg0 — CHANGES_REQUESTED** [review]
Your doc looks good to me. It just needs to be relocated at:
`/arbitrum-docs/for-devs/third-party-docs/USDC/<your-file-name.md>`

**Comment by anegg0** [comment]
Closed as this is a duplicate of an already merged PR.

**Pull request closed without merging**
