### PR TITLE
add nodereal to node providers

### PR DESCRIPTION
**Pull request by mahsamoosavi**

### CODE REVIEW

**Review by DZGoldman — APPROVED** [review]

**Review by DZGoldman — CHANGES_REQUESTED** [review]
let's keep the alphabetical order 🙏  @mahsamoosavi

**Comment by DZGoldman** [comment]
(for extra credit: auto-sort / render via mdx widget (obviously not at all necessary))

**Comment by mahsamoosavi** [comment]
> let's keep the alphabetical order 🙏 @mahsamoosavi

Oh sorry did not even realized there are ordered alphabetically!

**Comment by mahsamoosavi** [comment]
> (for extra credit: auto-sort / render via mdx widget (obviously not at all necessary))

Didn't know how so just did it old school 👵

**Review by DZGoldman — APPROVED** [review]

**Pull request merged**
