### PR TITLE
adds Envio to Arbitrum Developer Docs in 3rd Party section for walkthrough guide

### PR DESCRIPTION
**Pull request by SvenMuller95**
Adds Envio to 3rd party docs as a supported data indexing framework and data analytics for Arbitrum networks. 

Contributor License Agreement has been signed. 

https://portal.arbitrum.io/projects/infra-and-tools?chains=arbitrum-one_arbitrum-nova&project=envio

### CODE REVIEW

**Comment by SvenMuller95** [comment]
Made a typo in github username, wrote SvenMueller95, instead of SvenMuller95. Resigned the form using correct username.

**Comment by SvenMuller95** [comment]
Hi @hkalodner, upon further inspection, I have updated my git commit email settings as per cla-bot's suggestions (point 3). My email was set to private and therefore using "102...+SvenMuller95@users.noreply.github.com" instead of public profile email. It should now use my public profile email, and how this is the resolution. 

If this doesn't work, please advise how we can move passed this check. 

I have signed the contribution license agreement (cla).

**Comment by DenhamPreen** [comment]
Hi, also from envio to help, I have signed the form and will fork this into another pr to see if that works 👍

**Comment by DenhamPreen** [comment]
https://github.com/OffchainLabs/arbitrum-docs/pull/975

**Comment by hkalodner** [comment]
@cla-bot check

**Comment by hkalodner** [comment]
Looks like we're good in the other branch 🙏

**Comment by symbolpunk** [comment]
Closing in favor of https://github.com/OffchainLabs/arbitrum-docs/pull/975

**Pull request closed without merging**
