### PR TITLE
Added Alchemy

### PR DESCRIPTION
**Pull request by vardhanshorewala**
Hey there - Added Alchemy's Ethereum development framework as an additional option for developers. Have used it in the past and is extremely lightweight and easily deployable.

### CODE REVIEW

**Review by DZGoldman — CHANGES_REQUESTED** [review]
hi @vardhanshorewala — I think it would make more sense to link directly to the sdk, maybe https://docs.alchemy.com/reference/alchemy-sdk-quickstart is the best link? what do you think?

**Comment by vardhanshorewala** [comment]
hey @DZGoldman — i agree with your suggestion as it makes it more specific. thanks!

**Comment by DZGoldman** [comment]
@vardhanshorewala great — would you mind pushing the update + signing our CLA? then LGTM!

**Comment by DZGoldman** [comment]
@cla-bot check

**Review by DZGoldman — APPROVED** [review]

**Pull request merged**
