### PR TITLE
feat: add chainnodes as hosted node provider

### PR DESCRIPTION
**Pull request by koraykoska**
Add Chainnodes to the list of node providers.

[Chainnodes](https://www.chainnodes.org/) is a node provider with low latency and affordable prices and recently added support for Arbitrum.

### CODE REVIEW

**Comment by koraykoska** [comment]
I signed the cla now. How can I make it re-build the action?

**Comment by DZGoldman** [comment]
Hi @koraykoska  ! Apologies for the delay — we have a new process for listing on this page. Do me a favor and submit a request via [this form](https://docs.google.com/forms/d/e/1FAIpQLSdw0U-9LcLuih5TZ_QghS-S_MS4wCKSEigA_IQEza_hFmNVow/viewform); upon acceptance, chainnodes will be listed both here and on https://portal.arbitrum.one/#nodeproviders :) thanks!

**Comment by koraykoska** [comment]
@DZGoldman Thanks for the follow-up. I just submitted the form. Please let me know if you need anything else.

**Comment by koraykoska** [comment]
@DZGoldman Is there anything else you need? I have not received any follow ups

**Comment by koraykoska** [comment]
@DZGoldman Still haven't heard back from the form. Do you need anything else from us?

**Pull request closed without merging**
