### PR TITLE
Add Blast

### PR DESCRIPTION
**Pull request by mihaic01**
Added Blast in alphabetical order.

### CODE REVIEW

**Comment by DZGoldman** [comment]
Hi @mihaic01, we have a new process for listing on this page. Do me a favor and submit a request via [this form](https://docs.google.com/forms/d/e/1FAIpQLSdw0U-9LcLuih5TZ_QghS-S_MS4wCKSEigA_IQEza_hFmNVow/viewform); upon acceptance, Blast will be listed both here and on https://portal.arbitrum.one/#nodeproviders :) thanks!

**Comment by mihaic01** [comment]
Hey @DZGoldman ,

I submitted the form but i saw that we are only listed on https://portal.arbitrum.one/#nodeproviders , not on this page. We should also be listed here https://portal-nova.arbitrum.io/ since i provided the details that we support also Arbitrum Nova.

**Comment by DZGoldman** [comment]
@mihaic01 will update the nova portal and the docs page! If you could sign the CLA, then lfgm!

**Comment by DZGoldman** [comment]
@cla-bot check

**Review by DZGoldman — APPROVED** [review]

**Pull request merged**
