### PR TITLE
docs for using the graph on arbitrum

### PR DESCRIPTION
**Pull request by alinobrasil**
Here are the most up to date docs on getting started with The Graph. 
Arbitrum One and Aribtrum Sepolia are supported on [Subgraph Studio](https://thegraph.com/studio)!

### CODE REVIEW

**Comment by hkalodner** [comment]
@cla-bot check

**Comment by anegg0** [comment]
> Here are the most up to date docs on getting started with The Graph. Arbitrum One and Aribtrum Sepolia are supported on [Subgraph Studio](https://thegraph.com/studio)!

Hi, @alinobrasil. Thank you for sharing TheGraph-related content with us. 
Our team will review your PR shortly, and we'll let you know if any questions arise.

**Comment by anegg0** [comment]
> Here are the most up to date docs on getting started with The Graph. Arbitrum One and Aribtrum Sepolia are supported on [Subgraph Studio](https://thegraph.com/studio)!

Hey @alinobrasil,
Your content looks good!
I'd to push some suggestions to your fork so we can merge them into our docs. It looks like I don't have permission to `https://github.com/alinobrasil/arbitrum-docs`. Would it be OK for me to push a branch to your repo?

**Comment by alinobrasil** [comment]
Hi @anegg0 
I've added you as a collaborator!
Thanks!!

**Comment by anegg0** [comment]
> Hi @anegg0, I've added you as a collaborator! Thanks!!

Thanks! I opened a PR on your fork. Feel free to merge it to master and push it to this PR. I'll gladly add your content to our repo.

**Comment by alinobrasil** [comment]
Thanks @anegg0 ! I've merged the changes.

**Review by anegg0 — APPROVED** [review]

**Comment by anegg0** [comment]
> Thanks @anegg0 ! I've merged the changes.

Merging now, thank you :)

**Pull request merged**
