### PR TITLE
Add LearnWeb3 Faucets - Arbitrum Sepolia and Ethereum Sepolia

### PR DESCRIPTION
**Pull request by haardikk21**
Adds links to LearnWeb3's Arbitrum Sepolia and Ethereum Sepolia faucets to the docs

### CODE REVIEW

**Comment by hkalodner** [comment]
@cla-bot check

**Review by mahsamoosavi — APPROVED** [review]

**Comment by mahsamoosavi** [comment]
Hey @haardikk21! This project must be first added to the [Arbitrum Portal](https://portal.arbitrum.io) in order for us to be able to add it to our docs. For more instructions on how to do this please see [here](https://docs.arbitrum.io/for-devs/third-party-docs/contribute).

**Comment by haardikk21** [comment]
> Hey @haardikk21! This project must be first added to the [Arbitrum Portal](https://portal.arbitrum.io) in order for us to be able to add it to our docs. For more information on how to do this please see [here](https://docs.arbitrum.io/for-devs/third-party-docs/contribute).

I tried that. The Google Form link to submit for verification says it is closed and not accepting responses anymore.

**Comment by mahsamoosavi** [comment]
> > Hey @haardikk21! This project must be first added to the [Arbitrum Portal](https://portal.arbitrum.io) in order for us to be able to add it to our docs. For more information on how to do this please see [here](https://docs.arbitrum.io/for-devs/third-party-docs/contribute).
> 
> I tried that. The Google Form link to submit for verification says it is closed and not accepting responses anymore.
> 
> EDIT: Nevermind, I found the newer form - it's linked on the actual Portal website. The docs point to an older version it seems.

yea will get that fixed soon!

**Comment by haardikk21** [comment]
> > > Hey @haardikk21! This project must be first added to the [Arbitrum Portal](https://portal.arbitrum.io) in order for us to be able to add it to our docs. For more information on how to do this please see [here](https://docs.arbitrum.io/for-devs/third-party-docs/contribute).
> > 
> > 
> > I tried that. The Google Form link to submit for verification says it is closed and not accepting responses anymore.
> > EDIT: Nevermind, I found the newer form - it's linked on the actual Portal website. The docs point to an older version it seems.
> 
> yea will get that fixed soon!

Alright. I've submitted to the form. Can we re-open the PR and wait for merge until added to Portal?

**Pull request merged**
