### PR TITLE
docs: 1 char typo grammar update

### PR DESCRIPTION
**Pull request by bertmiller**
I was reading the docs for Nitro and stumbled for a second on the reference to "includes" in plural. I think "include" is what you actually meant here.

Apologizes for the 1 character change but it tripped me up for a moment and I thought it might someone else too :)

### CODE REVIEW

**Review by symbolpunk — APPROVED** [review]
Thank you! Great catch 🙏

**Comment by symbolpunk** [comment]
@bertmiller would you mind following the instructions [here](https://github.com/OffchainLabs/arbitrum-docs/pull/1104#issuecomment-2010370087)? Will merge once signed - thanks again.

**Comment by hkalodner** [comment]
@cla-bot check

**Comment by hkalodner** [comment]
Thank you ser! Had to double-take since I'm used to airdrop farmers 🤣

**Pull request merged**
