### PR TITLE
Update the NOWNodes availability

### PR DESCRIPTION
**Pull request by AnnaNodes**
Hello,

Could you please update the availability of NOWNodes access to the Arbitrum nodes?

### CODE REVIEW

**Comment by DZGoldman** [comment]
Hi @AnnaNodes ! Can you confirm that NowNodes supports the Arbitrum Nova network and the Arbitrum Goerli Rollup Testnet? I couldn't find any reference to either in the [docs](https://documenter.getpostman.com/view/13630829/TVmFkLwy#documentation) (the [site](https://nownodes.io/nodes/arbitrum) mentions "testnet" but not Nova / or multiple mainnet chains

**Review by DZGoldman — COMMENTED** [review]
Hi @AnnaNodes ! Can you confirm that NowNodes supports the Arbitrum Nova network and the Arbitrum Goerli Rollup Testnet? I couldn't find any reference to either in the [docs](https://documenter.getpostman.com/view/13630829/TVmFkLwy#documentation) (the [site](https://nownodes.io/nodes/arbitrum) mentions "testnet" but not Nova / or multiple mainnet chains)

**Comment by AnnaNodes** [comment]
Hi @DZGoldman !

We will fix the [Arbitrum page](https://nownodes.io/nodes/arbitrum) accordingly. We do provide dedicated access to any Arbitrum nodes.

**Comment by DZGoldman** [comment]
@AnnaNodes great - we'll update our dev docs once the info is live on the NOWNodes site 👍

**Comment by AnnaNodes** [comment]
Hi @DZGoldman !

Could you clarify, where you require to provide the information on our website?
As we provide dedicated access it already means that the client can access any Arbitrum node.

We will add any information on our website, that you require, but please specify what exactly you what us to add.

**Comment by DZGoldman** [comment]
Hi @AnnaNodes, the two pages that it would be nice to have more info on are the [docs](https://documenter.getpostman.com/view/13630829/TVmFkLwy#intro) and the [arbitrum page](https://nownodes.io/nodes/arbitrum):

- [Docs](https://documenter.getpostman.com/view/13630829/TVmFkLwy#intro)
On this page, I currently don't see any of the 3 Arbitrum Nodes listed anywhere; i.e., nothing about Arbitrum under [list of available proxies](https://documenter.getpostman.com/view/13630829/TVmFkLwy#list-of-available-proxies) and nothing under [proxies available upon request](https://documenter.getpostman.com/view/13630829/TVmFkLwy#list-of-proxies-available-upon-request); am I missing it?
- [Arbitrum NOWNodes page](https://nownodes.io/nodes/arbitrum)
Here, anywhere we can explicitly reference the 3 different Arbitrum chains offered would be nice; i.,e instead of 
>Connect to full Arbitrum node, block explorer and testnet now!

 how about 

> Connect to the Arbitrum One and Arbitrum Nova mainnet chains, and the Arbitrum Goerli Testnet now! 

And below, 

> NOWNodes as a service can provide you with access to 58 nodes, one of which is the Arbitrum node`

should this be

>  NOWNodes as a service can provide you with access to 58 nodes, three of which are Arbitrum nodes

?

**Review by DZGoldman — CHANGES_REQUESTED** [review]
pending NowNodes site update

**Comment by DZGoldman** [comment]
Hi @AnnaNodes, I'm going to close this for now; feel free to reopen when ready; thanks!

**Pull request closed without merging**
