### PR TITLE
feat: add flair indexing

### PR DESCRIPTION
**Pull request by kasrakhosravi**
Screenshot 2023-10-22 at 17 05 43

### CODE REVIEW

**Comment by hkalodner** [comment]
@cla-bot check

**Comment by kasrakhosravi** [comment]
> Hi @kasrakhosravi - would you mind following the third-party content contribution guidance located [here](https://docs.arbitrum.io/for-devs/third-party-docs/contribute) for this?
> 
> This seems like a great candidate for a concept doc describing what Flair is, and/or a quickstart targeted at Arbitrum developers.

Thanks for looking into this @symbolpunk 

I added this docs as a `quickstart` under `third-party content`. let me know if there were any further comments

**Review by symbolpunk — APPROVED** [review]

**Comment by symbolpunk** [comment]
@kasrakhosravi once you pull from `master`, this should be good to go. Thanks for the patience!

**Comment by kasrakhosravi** [comment]
Hey @Taranpreet26311 @symbolpunk @edfelten @hkalodner :)

Can we get this PR merged in?

**Comment by TucksonDev** [comment]
Thanks for your contribution @kasrakhosravi !

**Pull request merged**
