### PR TITLE
Add Chronicle to Oracles page

### PR DESCRIPTION
**Pull request by biancabuzea200**
1. Audience: developers that need to integrate Oracles
2. Problem: learning how to integrate with Chronicle Oracles
3. Discovery: Chronicle Oracles
4. Document type: Quickstart
5. Policy acknowledgment (Third-party docs only): Do you agree to the third-party content policy outlined within "Contribute docs"? yes

Chronicle links:
- docs: https://docs.chroniclelabs.org/
- website: https://chroniclelabs.org/

### CODE REVIEW

**Comment by biancabuzea200** [comment]
Hi, team. I signed the Contributor License Agreement, but the check still fails for some reason.

**Comment by anegg0** [comment]
> Hi, team. I signed the Contributor License Agreement, but the check still fails for some reason.

Hi, @biancabuzea200, and apologies for the delay.
We'll be happy to include your content once your project is validated. To do that, you need to submit your project to [Arbitrum portal](https://portal.arbitrum.io/) by filling out [this form](https://forms.gle/Vzzz39VLakHJ57ib7))

**Comment by hkalodner** [comment]
@cla-bot check

**Comment by biancabuzea200** [comment]
Hi, @anegg0, @hkalodner. Thank you very much for your support. I submitted the form. Please let me know if there is anything else I should do.

**Comment by biancabuzea200** [comment]
Hi, @anegg0, @hkalodner. I believe the form has been validated, as Chronicle got featured on your ecosystem portal. Let me know please if there is anything else left to do to finalize this.

**Review by anegg0 — APPROVED** [review]
LGTM

**Comment by anegg0** [comment]
Hi @biancabuzea200, your content has been merged [on another PR](https://github.com/OffchainLabs/arbitrum-docs/pull/1721) to do it faster (you would've needed to update your fork, otherwise). Thank you for your patience and feel free to let us know if you need additional edits.

**Pull request closed without merging**
