### PR TITLE
Add BlockPI to Arb Goerli providers

### PR DESCRIPTION
**Pull request by Mummyhap**
We just launched rpc service for Arbitrum Goerli. Thanks!
https://arbitrum-goerli.blockpi.network/v1/rpc/public

### CODE REVIEW

**Comment by TucksonDev** [comment]
@cla-bot check

**Comment by TucksonDev** [comment]
Hey @Mummyhap ! Thanks for opening this PR. We require contributors to sign the CLA from the cla-bot. Please, let us know when you sign it so we can verify it and merge these changes.
Thanks!

**Comment by Mummyhap** [comment]
I think I already signed the documents.

**Comment by TucksonDev** [comment]
@cla-bot check

**Pull request merged**
