### PR TITLE
Update solidity-support.mdx

### PR DESCRIPTION
**Pull request by NatPDeveloper**
## Overview:

It appears L1 gas is deducted before the contract has the ability to measure gas left. If someone has a link to the code where this occurs that would be helpful for me.

## Features Added:

- add gasleft() docs. 

## Example:

https://goerli.arbiscan.io/tx/0xaab3167237132bd51eaf14503a016ce764bd733145f2039035ffc45043af08ba#txninfo

This simple transaction logs `gasleft()` at the first possible moment as well as `tx.gasprice`. Because `gasleft()` is `6,784` at the time of execution, total gas used is `32,630` and L1/L2 gas respectively are `9,896` and `22,734` it appears the L1 gas is already deducted from the `gasleft()` precompile.

Gas limit - `gasleft()` 37,862 - 6,784 = 31,078 where 32,630 total gas is used means that the remainder of the function used 1,552 gas.

Contract used:

```
pragma solidity 0.8.16;

contract GasStation {
    event Stats(uint gasUsed, uint gasPrice);
    function printStats() external {
        emit Stats(gasleft(), tx.gasprice);
    }
}
```

More advanced contract:

```
pragma solidity 0.8.16;

import "./ArbGasInfo.sol";

contract GasStation {
    uint public GAS_OVERHEAD = 50_000;
    ArbGasInfo public immutable ARB_NITRO_ORACLE = ArbGasInfo(0x000000000000000000000000000000000000006C);
    
    event Stats(uint gasUsed, uint gasPrice, uint currentTxL1GasFees, uint total);
    function printStats() external {
        uint _gasUsed = gasleft();
        uint gasWei = tx.gasprice;
        uint l1CostWei = ARB_NITRO_ORACLE.getCurrentTxL1GasFees();
        uint total = gasWei * (_gasUsed - gasleft() + GAS_OVERHEAD) + l1CostWei;
        emit Stats(gasleft(), gasWeiZ, l1CostWei, total);
    }
}
```

### CODE REVIEW

**Comment by TucksonDev** [comment]
The definition is not completely accurate. The part of gas used for posting on L1 is intrinsic, meaning that it is used before any code runs. Thus, gasleft() can never take it into account.

**Comment by NatPDeveloper** [comment]
> The definition is not completely accurate. The part of gas used for posting on L1 is intrinsic, meaning that it is used before any code runs. Thus, gasleft() can never take it into account.

Ok, feel free to share what you think it should be updated too and I'll update the PR.

**Comment by TucksonDev** [comment]
How about this?

gasleft() formerly known as msg.gas works the same way it does on Ethereum for L2 gas. The gas used for posting on L1 is intrinsic, meaning that it is used before any code runs. See how to estimate gas for a detailed breakdown on how gas is calculated.
(Add the appropriate formatting and links, please)

**Comment by NatPDeveloper** [comment]
> gasleft() formerly known as msg.gas works the same way it does on Ethereum for L2 gas. The gas used for posting on L1 is intrinsic, meaning that it is used before any code runs. See how to estimate gas for a detailed breakdown on how gas is calculated.

updated

**Comment by TucksonDev** [comment]
Thanks. Can you also sign the CLA?

**Comment by NatPDeveloper** [comment]
> Hey! It looks like the CLA is not signed. I'm going to close this for now, but feel free to reopen once it is signed.blue_heartorange_heart

No worries. I'm not going to sign. Feels kind of weird having to sign a contract just to submit something I put together for free. At least that's a first for me. You're also doxing yourself.

**Pull request closed without merging**
