### PR TITLE
Update monitoring-tools-block-explorers.mdx

### PR DESCRIPTION
**Pull request by daizhengxue**
add chainbase company link

### CODE REVIEW

**Comment by TucksonDev** [comment]
@cla-bot check

**Comment by hkalodner** [comment]
@cla-bot check

**Comment by TucksonDev** [comment]
Hey @daizhengxue , thanks for opening this PR. We are working right now in a framework for contributions from third party services and we will soon have a clear vision about that type of content. I'll leave this PR open for now, but please expect some delay into reviewing it and giving you a response, which will be based on the final version of that framework.

**Comment by daizhengxue** [comment]
sure
thank you for the review.

**Review by symbolpunk — APPROVED** [review]

**Pull request merged**
