### PR TITLE
SubQuery Indexer Featured

### PR DESCRIPTION
**Pull request by bgodlin**
Hello Arbitrum team,

We are submitting this contribution with the intention of incorporating SubQuery into your project documentation. [Entry in Portal](https://portal.arbitrum.io/projects?chains=arbitrum-one_arbitrum-nova&subcategories=infra-and-tools-other&project=subquery). 

Kindly inform us if any adjustments are necessary.

### CODE REVIEW

**Comment by hkalodner** [comment]
@cla-bot check

**Comment by jamesbayly** [comment]
I've just signed the CLA under SubQuery Pte Ltd, sorry about the delay @symbolpunk

**Comment by hkalodner** [comment]
@cla-bot check

**Comment by hkalodner** [comment]
Thanks! All set on the CLA side

**Review by symbolpunk — APPROVED** [review]
TYSM!

**Comment by symbolpunk** [comment]
@jamesbayly @bgodlin if you pull from `master` into your remote, we'll be unblocked on merging this. Thanks again, looks great 👍

**Comment by symbolpunk** [comment]
@bgodlin thanks, looks like another PR snuck into `master` after you pulled, mind doing it again?

(cc @hkalodner in case there's a way for us to override)

**Review by symbolpunk — APPROVED** [review]

**Pull request merged**
