### PR TITLE
Update monitoring-tools-block-explorers.mdx

### PR DESCRIPTION
**Pull request by sneg55**
added alternative block explorer

### CODE REVIEW

**Comment by sneg55** [comment]
I already signed Contributor License Agreement  but still see this cla-bot reply 🤔  can you please check @edfelten @hkalodner

**Comment by hkalodner** [comment]
@cla-bot check

**Comment by hkalodner** [comment]
Thanks! Sorry about the delay 🙏

**Comment by sneg55** [comment]
@hkalodner can you help me find an appropriate contact for review/approval? Thanks!

**Comment by symbolpunk** [comment]
@sneg55 we're just about to restructure this page to be more of [an objective reference doc](https://docs.arbitrum.io/for-devs/contribute#document-type-conventions) with less marketing language - someone from our team will follow up when it's ready for this addition. Thanks for the patience!

**Comment by mahsamoosavi** [comment]
> @sneg55 we're just about to restructure this page to be more of [an objective reference doc](https://docs.arbitrum.io/for-devs/contribute#document-type-conventions) with less marketing language - someone from our team will follow up when it's ready for this addition. Thanks for the patience!

@sneg55 you could now find DexGuru added to our [docs](https://docs.arbitrum.io/for-devs/dev-tools-and-resources/monitoring-tools-block-explorers). I am closing the PR at this moment. We appreciate your contributions 💙

**Pull request closed without merging**
