### PR TITLE
Fix minor grammar errors

### PR DESCRIPTION
**Pull request by eljobe**
Three minor changes.

1. "why questions" -> "why" questions
2. missing "that"
3. RBlock -> RBlocks (in a plural context.)

### CODE REVIEW

**Comment by eljobe** [comment]
I have signed the CLA twice now. I'm not sure how to retrigger the `verification/cla-signed` check. Help?

**Comment by hkalodner** [comment]
@cla-bot check

**Comment by hkalodner** [comment]
There's a manual process of adding people so takes a bit to go through

**Review by anegg0 — APPROVED** [review]
These are valid edits (by my book). Thanks, @eljobe!

**Pull request merged**
